const assets = {
  icons: {
    email: require("@/assets/icons/email.png"),
    facebook: require("@/assets/icons/facebook.png"),
    instagram: require("@/assets/icons/instagram.png"),
    linkedIn: require("@/assets/icons/linkedin.png"),
    pinterest: require("@/assets/icons/pinterest.png"),
    reddit: require("@/assets/icons/reddit.png"),
    twitter: require("@/assets/icons/twitter.png"),
    whatsapp: require("@/assets/icons/whatsapp.png"),
  },
  image: {
    logo: require("@/assets/images/logo.png"),
    Flogo: require("@/assets/images/Flogo.png"),
    mobassher: require("@/assets/images/mobassher.png"),
    notFound: require("@/assets/images/notFound.png"),
    noImage: require("@/assets/No-Image.png"),
  },
  portfolio: {
    dohaCover: require("@/assets/portfolio/Ad-doha.png"),
    dohaFull: require("@/assets/portfolio/Ad-doha.png"),
    bikeManageCover: require("@/assets/portfolio/Bike-Managemt.png"),
    bikeManageFull: require("@/assets/portfolio/Bike-Management-full.png"),
    groceryCover: require("@/assets/portfolio/Grocery-Management.png"),
    groceryFull: require("@/assets/portfolio/Grocery-Management-full.png"),
    influencerCover: require("@/assets/portfolio/ifluencer.png"),
    influencerFull: require("@/assets/portfolio/influencer-full.png"),
    irdfCover: require("@/assets/portfolio/irdf.png"),
    irdfFull: require("@/assets/portfolio/irdf-full.png"),
    masfbdCover: require("@/assets/portfolio/masfbd.png"),
    masfbdFull: require("@/assets/portfolio/masfbdfull.png"),
    mediaCover: require("@/assets/portfolio/media.png"),
    mediaFull: require("@/assets/portfolio/mediafull.png"),
    mmitCover: require("@/assets/portfolio/mmit.png"),
    mmitFull: require("@/assets/portfolio/mmit.png"),
    mobileCover: require("@/assets/portfolio/mobileapp.png"),
    mobileFull: require("@/assets/portfolio/mobile-app-full.png"),
    ngitCover: require("@/assets/portfolio/NGIT.png"),
    ngitFull: require("@/assets/portfolio/NGIT.png"),
    petAdoptionCover: require("@/assets/portfolio/Pet-Adoption.png"),
    petAdoptionFull: require("@/assets/portfolio/Pet-Adoption-full.png"),
    projectCover: require("@/assets/portfolio/Project-Managemen.png"),
    projectFull: require("@/assets/portfolio/Project-Management-full.png"),
    sahanutrustCover: require("@/assets/portfolio/sahanutrust.png"),
    sahanutrustFull: require("@/assets/portfolio/sahanuTrust-full.png"),
    saveHumanityCover: require("@/assets/portfolio/Save-Humanity.png"),
    saveHumanityFull: require("@/assets/portfolio/save-Humanity-full.png"),
    wattsCover: require("@/assets/portfolio/Watts-basketball.png"),
    wattsFull: require("@/assets/portfolio/Watts-basketball-full.png"),
    uifryCover: require("@/assets/portfolio/uifry.png"),
    uifryFull: require("@/assets/portfolio/uifry-full.png"),
    abdullahAhsanCover: require("@/assets/portfolio/Professor-Abdullah-ahsan.png"),
    abdullahAhsanFull: require("@/assets/portfolio/Professor-Abdullah-ahsan.png"),
  },
};

export default assets;
